# ==================== 平台适配 ====================

if(UNIX AND NOT APPLE)
    set(BERT_RPATH_TARGETS "")
    if(TARGET bert_inference_client)
        list(APPEND BERT_RPATH_TARGETS bert_inference_client bert_benchmark_client)
    endif()
    if(TARGET multimodal_inference_server)
        list(APPEND BERT_RPATH_TARGETS multimodal_inference_server)
    endif()
    if(TARGET emotion_inference_server)
        list(APPEND BERT_RPATH_TARGETS emotion_inference_server)
    endif()
    if(TARGET static_site_test_server)
        list(APPEND BERT_RPATH_TARGETS static_site_test_server)
    endif()
    if(TARGET static_site_concurrency_bench)
        list(APPEND BERT_RPATH_TARGETS static_site_concurrency_bench)
    endif()
    if(TARGET core_tests)
        list(APPEND BERT_RPATH_TARGETS core_tests)
    endif()
    if(TARGET net_tests)
        list(APPEND BERT_RPATH_TARGETS net_tests)
    endif()
    foreach(target ${BERT_RPATH_TARGETS})
        set_target_properties(${target} PROPERTIES
            BUILD_RPATH "$ORIGIN"
            INSTALL_RPATH "$ORIGIN"
        )
    endforeach()
endif()

# 安装
set(BERT_INSTALL_TARGETS "")
if(TARGET bert_inference_client)
    list(APPEND BERT_INSTALL_TARGETS bert_inference_client bert_benchmark_client)
endif()
if(TARGET multimodal_inference_server)
    list(APPEND BERT_INSTALL_TARGETS multimodal_inference_server)
endif()
if(TARGET emotion_inference_server)
    list(APPEND BERT_INSTALL_TARGETS emotion_inference_server)
endif()
if(BERT_INSTALL_TARGETS)
    install(TARGETS ${BERT_INSTALL_TARGETS}
        RUNTIME DESTINATION bin
        COMPONENT Runtime
        EXCLUDE_FROM_ALL)
endif()

# 复制 ONNX Runtime 运行时库
file(GLOB ONNXRUNTIME_RUNTIME_LIBS "${ONNXRUNTIME_ROOT}/${BERT_ONNXRUNTIME_RUNTIME_GLOB}")
foreach(ONNXRUNTIME_RUNTIME_LIB ${ONNXRUNTIME_RUNTIME_LIBS})
    if(TARGET multimodal_inference_server)
        copy_runtime_files(multimodal_inference_server "${ONNXRUNTIME_RUNTIME_LIB}")
    endif()
    if(TARGET emotion_inference_server)
        copy_runtime_files(emotion_inference_server "${ONNXRUNTIME_RUNTIME_LIB}")
    endif()
    if(TARGET emotion_fusion_map_calibrator)
        copy_runtime_files(emotion_fusion_map_calibrator "${ONNXRUNTIME_RUNTIME_LIB}")
    endif()
endforeach()

if(EXISTS "${BERT_EXTRA_RUNTIME_DLL_ROOT}")
    if(WIN32)
        file(GLOB BERT_EXTRA_RUNTIME_LIBS
            "${BERT_EXTRA_RUNTIME_DLL_ROOT}/onnxruntime*.dll"
        )
    elseif(UNIX AND NOT APPLE)
        file(GLOB BERT_EXTRA_RUNTIME_LIBS
            "${BERT_EXTRA_RUNTIME_DLL_ROOT}/libonnxruntime*.so*"
        )
    endif()
    foreach(BERT_EXTRA_RUNTIME_LIB ${BERT_EXTRA_RUNTIME_LIBS})
        if(TARGET emotion_fusion_map_calibrator)
            copy_runtime_files(emotion_fusion_map_calibrator "${BERT_EXTRA_RUNTIME_LIB}")
        endif()
    endforeach()
endif()

# 复制 vcpkg 动态库依赖
if(WIN32 AND BERT_VCPKG_TRIPLET AND NOT VCPKG_RUNTIME_DLLS)
    file(GLOB VCPKG_RUNTIME_DLLS "${CMAKE_CURRENT_SOURCE_DIR}/vcpkg_installed/${BERT_VCPKG_TRIPLET}/bin/*.dll")
    set(BERT_RUNTIME_COPY_TARGETS "")
    if(TARGET bert_inference_client)
        list(APPEND BERT_RUNTIME_COPY_TARGETS bert_inference_client bert_benchmark_client)
    endif()
    if(TARGET multimodal_inference_server)
        list(APPEND BERT_RUNTIME_COPY_TARGETS multimodal_inference_server)
    endif()
    if(TARGET emotion_inference_server)
        list(APPEND BERT_RUNTIME_COPY_TARGETS emotion_inference_server)
    endif()
    if(TARGET static_site_test_server)
        list(APPEND BERT_RUNTIME_COPY_TARGETS static_site_test_server)
    endif()
    if(TARGET static_site_concurrency_bench)
        list(APPEND BERT_RUNTIME_COPY_TARGETS static_site_concurrency_bench)
    endif()
    if(TARGET core_tests)
        list(APPEND BERT_RUNTIME_COPY_TARGETS core_tests)
    endif()
    if(TARGET net_tests)
        list(APPEND BERT_RUNTIME_COPY_TARGETS net_tests)
    endif()
    if(TARGET storage_tests)
        list(APPEND BERT_RUNTIME_COPY_TARGETS storage_tests)
    endif()
    if(TARGET vector_tests)
        list(APPEND BERT_RUNTIME_COPY_TARGETS vector_tests)
    endif()
    if(TARGET config_tests)
        list(APPEND BERT_RUNTIME_COPY_TARGETS config_tests)
    endif()
    if(TARGET persona_runtime_tests)
        list(APPEND BERT_RUNTIME_COPY_TARGETS persona_runtime_tests)
    endif()
    if(TARGET gateway_service_tests)
        list(APPEND BERT_RUNTIME_COPY_TARGETS gateway_service_tests)
    endif()
    if(TARGET media_skill_tests)
        list(APPEND BERT_RUNTIME_COPY_TARGETS media_skill_tests)
    endif()
    foreach(target ${BERT_RUNTIME_COPY_TARGETS})
        copy_runtime_files(${target} ${VCPKG_RUNTIME_DLLS})
    endforeach()
endif()

if(UNIX AND NOT APPLE AND BERT_VCPKG_TRIPLET)
    file(GLOB VCPKG_RUNTIME_SOS "${CMAKE_CURRENT_SOURCE_DIR}/vcpkg_installed/${BERT_VCPKG_TRIPLET}/lib/*.so*")
    set(BERT_RUNTIME_COPY_TARGETS "")
    if(TARGET bert_inference_client)
        list(APPEND BERT_RUNTIME_COPY_TARGETS bert_inference_client bert_benchmark_client)
    endif()
    if(TARGET multimodal_inference_server)
        list(APPEND BERT_RUNTIME_COPY_TARGETS multimodal_inference_server)
    endif()
    if(TARGET emotion_inference_server)
        list(APPEND BERT_RUNTIME_COPY_TARGETS emotion_inference_server)
    endif()
    if(TARGET static_site_test_server)
        list(APPEND BERT_RUNTIME_COPY_TARGETS static_site_test_server)
    endif()
    if(TARGET static_site_concurrency_bench)
        list(APPEND BERT_RUNTIME_COPY_TARGETS static_site_concurrency_bench)
    endif()
    if(TARGET core_tests)
        list(APPEND BERT_RUNTIME_COPY_TARGETS core_tests)
    endif()
    if(TARGET net_tests)
        list(APPEND BERT_RUNTIME_COPY_TARGETS net_tests)
    endif()
    if(TARGET storage_tests)
        list(APPEND BERT_RUNTIME_COPY_TARGETS storage_tests)
    endif()
    if(TARGET vector_tests)
        list(APPEND BERT_RUNTIME_COPY_TARGETS vector_tests)
    endif()
    if(TARGET config_tests)
        list(APPEND BERT_RUNTIME_COPY_TARGETS config_tests)
    endif()
    if(TARGET persona_runtime_tests)
        list(APPEND BERT_RUNTIME_COPY_TARGETS persona_runtime_tests)
    endif()
    if(TARGET gateway_service_tests)
        list(APPEND BERT_RUNTIME_COPY_TARGETS gateway_service_tests)
    endif()
    if(TARGET media_skill_tests)
        list(APPEND BERT_RUNTIME_COPY_TARGETS media_skill_tests)
    endif()
    if(VCPKG_RUNTIME_SOS AND BERT_RUNTIME_COPY_TARGETS)
        set(_agentloom_vcpkg_runtime_stamp
            "${CMAKE_CURRENT_BINARY_DIR}/.agentloom-vcpkg-runtime.stamp")
        set(_agentloom_vcpkg_runtime_copy_commands "")
        foreach(runtime_file IN LISTS VCPKG_RUNTIME_SOS)
            list(APPEND _agentloom_vcpkg_runtime_copy_commands
                COMMAND ${CMAKE_COMMAND} -E copy_if_different
                    "${runtime_file}"
                    "${CMAKE_CURRENT_BINARY_DIR}")
        endforeach()

        # Linux 单配置构建的可执行文件共享同一输出目录；统一复制可避免多个
        # POST_BUILD 命令并行写入同名版本化 so/symlink 时发生随机竞态。
        add_custom_command(
            OUTPUT "${_agentloom_vcpkg_runtime_stamp}"
            ${_agentloom_vcpkg_runtime_copy_commands}
            COMMAND ${CMAKE_COMMAND} -E touch "${_agentloom_vcpkg_runtime_stamp}"
            DEPENDS ${VCPKG_RUNTIME_SOS}
            VERBATIM)
        add_custom_target(agentloom_vcpkg_runtime_files
            DEPENDS "${_agentloom_vcpkg_runtime_stamp}")

        foreach(target IN LISTS BERT_RUNTIME_COPY_TARGETS)
            add_dependencies(${target} agentloom_vcpkg_runtime_files)
        endforeach()
    endif()
endif()

# 复制 CUDA / cuDNN 运行时库（如果存在）
if(EXISTS "${CUDA_RUNTIME_DLL_ROOT}")
    if(WIN32)
        file(GLOB CUDA_RUNTIME_LIBS "${CUDA_RUNTIME_DLL_ROOT}/*.dll")
    elseif(UNIX AND NOT APPLE)
        file(GLOB CUDA_RUNTIME_LIBS "${CUDA_RUNTIME_DLL_ROOT}/*.so*")
    endif()
    if(TARGET multimodal_inference_server)
        copy_runtime_files(multimodal_inference_server ${CUDA_RUNTIME_LIBS})
    endif()
    if(TARGET emotion_fusion_map_calibrator)
        copy_runtime_files(emotion_fusion_map_calibrator ${CUDA_RUNTIME_LIBS})
    endif()
endif()
